############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


######################################################################
#
#  配置数据源信息
#
######################################################################
spring:
  # 配置真实数据源
  shardingsphere:
    datasource:
      names: ds-master-0,ds-master-1,ds-direct
      # 配置第1个数据源
      ds-master-0:
        type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
        driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
        # 数据库url连接
        url: jdbc:mysql://localhost:3306/test0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        jdbc-url: jdbc:mysql://localhost:3306/test0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password:
      # 配置第2个数据源
      ds-master-1:
        type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
        driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
        # 数据库url连接
        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password:
      # 配置第3个数据源
      ds-direct:
        type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
        driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
        url: jdbc:mysql://localhost:3306/foodieshopdev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        jdbc-url: jdbc:mysql://localhost:3306/foodieshopdev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password:
    # 配置 user 表规则
    sharding:
      defaultDataSourceName: ds-direct
      tables:
        test_user:
          actual-data-nodes: ds-master-$->{0..1}.test_user_$->{0..1}
          # 配置分表策略 主键取模 0在0表 1在1表
          table-strategy:
            inline:
              #分片列名称
              sharding-column: id
              #分片算法行表达式
              algorithm-expression: test_user_$->{id % 2}
          # 主键策略 雪花算法
          key-generator:
            column: id
            type: SNOWFLAKE
      # 配置分库策略 主键取模0在0库 1在1库
      default-database-strategy:
        inline:
          sharding-column: id
          #分片算法行表达式
          algorithm-expression: ds-master-$->{id % 2}
    # 打开sql控制台输出日志
    props:
      sql:
        show: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    database: 0
    #cluster:
    #  nodes: 192.168.1.1:6379,192.168.1.2:6379,192.168.1.3:6379,192.168.1.4:6379,192.168.1.5:6379,192.168.1.6:6379
    #password: 123
    #cloud:
      #sentinel:
      #transport:
      #dashboard: 127.0.0.1:8082
      #eager: true

