############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


######################################################################
#
#  配置数据源信息
#
######################################################################
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodieshopdev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password:
  redis:
    # host: 127.0.0.1
    # port: 6379
    # password: 123
    # database: 0
    cluster:
      nodes: 192.168.1.1:6379,192.168.1.2:6379,192.168.1.3:6379,192.168.1.4:6379,192.168.1.5:6379,192.168.1.6:6379
    password: 123




